version: "3.7"

services:
  webserver:
    build:
      context: .
      dockerfile: "./docker/services/php81/Dockerfile"
    container_name: "framework-webserver"
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html:cached
      - ./docker/vhosts:/etc/apache2/sites-enabled
      - ./docker/services/php81/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_NAME: "framework"
      DB_USERNAME: "dev"
      DB_PASSWORD: "dev"

  database:
     build:
       context: "./docker/services/postgres"
     container_name: "framework-database"
     volumes:
       - ./sql:/docker-entrypoint-initdb.d/sql
       - ./sql/database.sql:/docker-entrypoint-initdb.d/1-database.sql
       - ./sql/data-mock.sql:/docker-entrypoint-initdb.d/2-data-mock.sql
     restart: "always"
     ports:
       - "5432:5432"
     environment:
       POSTGRES_DB: "framework"
       POSTGRES_USER: "dev"
       POSTGRES_PASSWORD: "dev"
